import AsyncStorage from "@react-native-async-storage/async-storage";
export const apiKey = "4ae25ed28196396194f9fd9b3af0a1ae";

export const equipment = {
  adventureGear: [
    {
      name: "Backpack (empty)",
      cost: "2 gp",
      weight: "2 lb.",
    },
    {
      name: "Barrel (empty)",
      cost: "2 gp",
      weight: "30 lb.",
    },
    {
      name: "Basket (empty)",
      cost: "4 sp",
      weight: "1 lb.",
    },
    {
      name: "Bedroll",
      cost: "1 sp",
      weight: "5 lb.",
    },
    {
      name: "Bell",
      cost: "1 gp",
      weight: "—",
    },
    {
      name: "Blanket, winter",
      cost: "5 sp",
      weight: "3 lb.",
    },
    {
      name: "Block and tackle",
      cost: "5 gp",
      weight: "5 lb.",
    },
    {
      name: "Bottle, wine, glass",
      cost: "2 gp",
      weight: "—",
    },
    {
      name: "Bucket (empty)",
      cost: "5 sp",
      weight: "2 lb.",
    },
    {
      name: "Caltrops",
      cost: "1 gp",
      weight: "2 lb.",
    },
    {
      name: "Candle",
      cost: "1 cp",
      weight: "—",
    },
    {
      name: "Canvas (sq. yd.)",
      cost: "1 sp",
      weight: "1 lb.",
    },
    {
      name: "Case, map or scroll",
      cost: "1 gp",
      weight: "0.5 lb.",
    },
    {
      name: "Chain (10 ft.)",
      cost: "30 gp",
      weight: "2 lb.",
    },
    {
      name: "Chalk, 1 piece",
      cost: "1 cp",
      weight: "—",
    },
    {
      name: "Chest (empty)",
      cost: "2 gp",
      weight: "25 lb.",
    },
    {
      name: "Crowbar",
      cost: "2 gp",
      weight: "5 lb.",
    },
    {
      name: "Firewood (per day)",
      cost: "1 cp",
      weight: "20 lb.",
    },
    {
      name: "Fishhook",
      cost: "1 sp",
      weight: "—",
    },
    {
      name: "Fishing net, 25 sq. ft.",
      cost: "4 gp",
      weight: "5 lb.",
    },
    {
      name: "Flask (empty)",
      cost: "3 cp",
      weight: "1.5 lb.",
    },
    {
      name: "Flint and steel",
      cost: "1 gp",
      weight: "—",
    },
    {
      name: "Grappling hook",
      cost: "1 gp",
      weight: "4 lb.",
    },
    {
      name: "Hammer",
      cost: "5 sp",
      weight: "2 lb.",
    },
    {
      name: "Ink (1 oz. vial)",
      cost: "8 gp",
      weight: "—",
    },
    {
      name: "Inkpen",
      cost: "1 sp",
      weight: "—",
    },
    {
      name: "Jug, clay",
      cost: "3 cp",
      weight: "9 lb.",
    },
    {
      name: "Ladder, 10-foot",
      cost: "5 cp",
      weight: "20 lb.",
    },
    {
      name: "Lamp, common",
      cost: "1 sp",
      weight: "1 lb.",
    },
    {
      name: "Lantern, bullseye",
      cost: "12 gp",
      weight: "3 lb.",
    },
    {
      name: "Lantern, hooded",
      cost: "7 gp",
      weight: "2 lb.",
    },
    {
      name: "Lock (very simple)",
      cost: "20 gp",
      weight: "1 lb.",
    },
    {
      name: "Lock (average)",
      cost: "40 gp",
      weight: "1 lb.",
    },
    {
      name: "Lock (good)",
      cost: "80 gp",
      weight: "1 lb.",
    },
    {
      name: "Lock (amazing)",
      cost: "150 gp",
      weight: "1 lb.",
    },
    {
      name: "Manacles",
      cost: "15 gp",
      weight: "2 lb.",
    },
    {
      name: "Manacles, masterwork",
      cost: "50 gp",
      weight: "2 lb.",
    },
    {
      name: "Mirror, small steel",
      cost: "10 gp",
      weight: "0.5 lb.",
    },
    {
      name: "Mug/Tankard, clay",
      cost: "2 cp",
      weight: "1 lb.",
    },
    {
      name: "Oil (1-pint flask)",
      cost: "1 sp",
      weight: "1 lb.",
    },
    {
      name: "Paper (sheet)",
      cost: "4 sp",
      weight: "—",
    },
    {
      name: "Parchment (sheet)",
      cost: "2 sp",
      weight: "—",
    },
    {
      name: "Pick, miner’s",
      cost: "3 gp",
      weight: "10 lb.",
    },
    {
      name: "Pitcher, clay",
      cost: "2 cp",
      weight: "5 lb.",
    },
    {
      name: "Piton",
      cost: "1 sp",
      weight: "0.5 lb.",
    },
    {
      name: "Pole, 10-foot",
      cost: "2 sp",
      weight: "8 lb.",
    },
    {
      name: "Pot, iron",
      cost: "5 sp",
      weight: "10 lb.",
    },
    {
      name: "Pouch, belt (empty)",
      cost: "1 gp",
      weight: "0.5 lb.",
    },
    {
      name: "Ram, portable",
      cost: "10 gp",
      weight: "20 lb.",
    },
    {
      name: "Rations, trail (per day)",
      cost: "5 sp",
      weight: "1 lb.",
    },
    {
      name: "Rope, hempen (50 ft.)",
      cost: "1 gp",
      weight: "10 lb.",
    },
    {
      name: "Rope, silk (50 ft.)",
      cost: "10 gp",
      weight: "5 lb.",
    },
    {
      name: "Sack (empty)",
      cost: "1 sp",
      weight: "0.5 lb.",
    },
    {
      name: "Sealing wax",
      cost: "1 gp",
      weight: "1 lb.",
    },
    {
      name: "Sewing needle",
      cost: "5 sp",
      weight: "—",
    },
    {
      name: "Signal whistle",
      cost: "8 sp",
      weight: "—",
    },
    {
      name: "Signet ring",
      cost: "5 gp",
      weight: "—",
    },
    {
      name: "Sledge",
      cost: "1 gp",
      weight: "10 lb.",
    },
    {
      name: "Soap (per lb.)",
      cost: "5 sp",
      weight: "1 lb.",
    },
    {
      name: "Spade or shovel",
      cost: "2 gp",
      weight: "8 lb.",
    },
    {
      name: "Spyglass",
      cost: "1,000 gp",
      weight: "1 lb.",
    },
    {
      name: "Tent",
      cost: "10 gp",
      weight: "20 lb.",
    },
    {
      name: "Torch",
      cost: "1 cp",
      weight: "1 lb.",
    },
    {
      name: "Vial, ink or potion",
      cost: "1 gp",
      weight: "1/10 lb.",
    },
    {
      name: "Waterskin",
      cost: "1 gp",
      weight: "4 lb.",
    },
    {
      name: "Whetstone",
      cost: "2 cp",
      weight: "1 lb.",
    },
  ],
  specialSubstancesAndItems: [
    {
      name: "Acid (flask)",
      cost: "10 gp",
      weight: "1 lb.",
    },
    {
      name: "Alchemist’s fire (flask)",
      cost: "20 gp",
      weight: "1 lb.",
    },
    {
      name: "Antitoxin (vial)",
      cost: "50 gp",
      weight: "—",
    },
    {
      name: "Everburning torch",
      cost: "110 gp",
      weight: "1 lb.",
    },
    {
      name: "Holy water (flask)",
      cost: "25 gp",
      weight: "1 lb.",
    },
    {
      name: "Smokestick",
      cost: "20 gp",
      weight: "0.5 lb.",
    },
    {
      name: "Sunrod",
      cost: "2 gp",
      weight: "1 lb.",
    },
    {
      name: "Tanglefoot bag",
      cost: "50 gp",
      weight: "4 lb.",
    },
    {
      name: "Thunderstone",
      cost: "30 gp",
      weight: "1 lb.",
    },
    {
      name: "Tindertwig",
      cost: "1 gp",
      weight: "—",
    },
  ],
  toolsAndSkillKits: [
    {
      name: "Alchemist’s lab",
      cost: "500 gp",
      weight: "40 lb.",
    },
    {
      name: "Artisan’s tools",
      cost: "5 gp",
      weight: "5 lb.",
    },
    {
      name: "Artisan’s tools, masterwork",
      cost: "55 gp",
      weight: "5 lb.",
    },
    {
      name: "Climber’s kit",
      cost: "80 gp",
      weight: "5 lb.",
    },
    {
      name: "Disguise kit",
      cost: "50 gp",
      weight: "8 lb.",
    },
    {
      name: "Healer’s kit",
      cost: "50 gp",
      weight: "1 lb.",
    },
    {
      name: "Holly and mistletoe",
      cost: "—",
      weight: "—",
    },
    {
      name: "Holy symbol, wooden",
      cost: "1 gp",
      weight: "—",
    },
    {
      name: "Holy symbol, silver",
      cost: "25 gp",
      weight: "1 lb.",
    },
    {
      name: "Hourglass",
      cost: "25 gp",
      weight: "1 lb.",
    },
    {
      name: "Magnifying glass",
      cost: "100 gp",
      weight: "—",
    },
    {
      name: "Musical instrument, common",
      cost: "5 gp",
      weight: "3 lb.",
    },
    {
      name: "Musical instrument, masterwork",
      cost: "100 gp",
      weight: "3 lb.",
    },
    {
      name: "Scale, merchant’s",
      cost: "2 gp",
      weight: "1 lb.",
    },
    {
      name: "Spell component pouch",
      cost: "5 gp",
      weight: "2 lb.",
    },
    {
      name: "Spellbook, wizard’s (blank)",
      cost: "15 gp",
      weight: "3 lb.",
    },
    {
      name: "Thieves’ tools",
      cost: "30 gp",
      weight: "1 lb.",
    },
    {
      name: "Thieves’ tools, masterwork",
      cost: "100 gp",
      weight: "2 lb.",
    },
    {
      name: "Tool, masterwork",
      cost: "50 gp",
      weight: "1 lb.",
    },
    {
      name: "Water clock",
      cost: "1,000 gp",
      weight: "200 lb.",
    },
  ],
  clothing: [
    {
      name: "Artisan’s outfit",
      cost: "1 gp",
      weight: "4 lb.",
    },
    {
      name: "Cleric’s vestments",
      cost: "5 gp",
      weight: "6 lb.",
    },
    {
      name: "Cold weather outfit",
      cost: "8 gp",
      weight: "7 lb.",
    },
    {
      name: "Courtier’s outfit",
      cost: "30 gp",
      weight: "6 lb.",
    },
    {
      name: "Entertainer’s outfit",
      cost: "3 gp",
      weight: "4 lb.",
    },
    {
      name: "Explorer’s outfit",
      cost: "10 gp",
      weight: "8 lb.",
    },
    {
      name: "Monk’s outfit",
      cost: "5 gp",
      weight: "2 lb.",
    },
    {
      name: "Noble’s outfit",
      cost: "75 gp",
      weight: "10 lb.",
    },
    {
      name: "Peasant’s outfit",
      cost: "1 sp",
      weight: "2 lb.",
    },
    {
      name: "Royal outfit",
      cost: "200 gp",
      weight: "15 lb.",
    },
    {
      name: "Scholar’s outfit",
      cost: "5 gp",
      weight: "6 lb.",
    },
    {
      name: "Traveler’s outfit",
      cost: "1 gp",
      weight: "5 lb.",
    },
  ],
  foodDrinkAndLodging: [
    {
      ale: [
        {
          name: "Gallon",
          cost: "2 sp",
          weight: "8 lb.",
        },
        {
          name: "Mug",
          cost: "4 cp",
          weight: "1 lb.",
        },
        {
          name: "Banquet (per person)",
          cost: "10 gp",
          weight: "—",
        },
        {
          name: "Bread, per loaf",
          cost: "2 cp",
          weight: "0.5 lb.",
        },
        {
          name: "Cheese, hunk of",
          cost: "1 sp",
          weight: "0.5 lb.",
        },
      ],
    },
    {
      innStay: [
        {
          name: "Good",
          cost: "2 gp",
          weight: "—",
        },
        {
          name: "Common",
          cost: "5 sp",
          weight: "—",
        },
        {
          name: "Poor",
          cost: "2 sp",
          weight: "—",
        },
      ],
    },
    {
      meals: [
        {
          name: "Good",
          cost: "5 sp",
          weight: "—",
        },
        {
          name: "Common",
          cost: "3 sp",
          weight: "—",
        },
        {
          name: "Poor",
          cost: "1 sp",
          weight: "—",
        },
        {
          name: "Meat, chunk of",
          cost: "3 sp",
          weight: "0.5 lb.",
        },
      ],
    },
    {
      wine: [
        {
          name: "Common (pitcher)",
          cost: "2 sp",
          weight: "6 lb.",
        },
        {
          name: "Fine (bottle)",
          cost: "10 gp",
          weight: "1.5 lb.",
        },
      ],
    },
  ],
  mountsAndRelatedGear: [
    {
      barding: [
        {
          name: "Medium creature",
          cost: "×2",
          weight: "×1",
        },
        {
          name: "Large creature",
          cost: "×4",
          weight: "×2",
        },
      ],
    },
    {
      name: "Bit and bridle",
      cost: "2 gp",
      weight: "1 lb.",
    },
    {
      name: "Dog, guard",
      cost: "25 gp",
      weight: "—",
    },
    {
      name: "Dog, riding",
      cost: "150 gp",
      weight: "—",
    },
    {
      name: "Donkey or mule",
      cost: "8 gp",
      weight: "—",
    },
    {
      name: "Feed (per day)",
      cost: "5 cp",
      weight: "10 lb.",
    },
    {
      horse: [
        {
          name: "Horse, heavy",
          cost: "200 gp",
          weight: "—",
        },
        {
          name: "Horse, light",
          cost: "75 gp",
          weight: "—",
        },
        {
          name: "Pony",
          cost: "30 gp",
          weight: "—",
        },
        {
          name: "Warhorse, heavy",
          cost: "400 gp",
          weight: "—",
        },
        {
          name: "Warhorse, light",
          cost: "150 gp",
          weight: "—",
        },
        {
          name: "Warpony",
          cost: "100 gp",
          weight: "—",
        },
      ],
    },
    {
      saddle: [
        {
          name: "Military",
          cost: "20 gp",
          weight: "30 lb.",
        },
        {
          name: "Pack",
          cost: "5 gp",
          weight: "15 lb.",
        },
        {
          name: "Riding",
          cost: "10 gp",
          weight: "25 lb.",
        },
      ],
    },
    {
      saddleExotic: [
        {
          name: "Military",
          cost: "60 gp",
          weight: "40 lb.",
        },
        {
          name: "Pack",
          cost: "15 gp",
          weight: "20 lb.",
        },
        {
          name: "Riding",
          cost: "30 gp",
          weight: "30 lb.",
        },
      ],
    },
    {
      name: "Saddlebags",
      cost: "4 gp",
      weight: "8 lb.",
    },
    {
      name: "Stabling (per day)",
      cost: "5 sp",
      weight: "—",
    },
  ],
  transport: [
    {
      name: "Carriage",
      cost: "100 gp",
      weight: "600 lb.",
    },
    {
      name: "Cart",
      cost: "15 gp",
      weight: "200 lb.",
    },
    {
      name: "Galley",
      cost: "30,000 gp",
      weight: "—",
    },
    {
      name: "Keelboat",
      cost: "3,000 gp",
      weight: "—",
    },
    {
      name: "Longship",
      cost: "10,000 gp",
      weight: "—",
    },
    {
      name: "Rowboat",
      cost: "50 gp",
      weight: "100 lb.",
    },
    {
      name: "Oar",
      cost: "2 gp",
      weight: "10 lb.",
    },
    {
      name: "Sailing ship",
      cost: "10,000 gp",
      weight: "—",
    },
    {
      name: "Sled",
      cost: "20 gp",
      weight: "300 lb.",
    },
    {
      name: "Wagon",
      cost: "35 gp",
      weight: "400 lb.",
    },
    {
      name: "Warship",
      cost: "25,000 gp",
      weight: "—",
    },
  ],
  spellCastingAndServices: [
    {
      name: "Coach cab",
      cost: "3 cp per mile",
    },
    {
      name: "Hireling, trained",
      cost: "3 sp per day",
    },
    {
      name: "Hireling, untrained",
      cost: "1 sp per day",
    },
    {
      name: "Messenger",
      cost: "2 cp per mile",
    },
    {
      name: "Road or gate toll",
      cost: "1 cp",
    },
    {
      name: "Ship’s passage",
      cost: "1 sp per mile",
    },
    {
      name: "Spell, 0-level",
      cost: "Caster level × 5 gp",
    },
    {
      name: "Spell, 1st-level",
      cost: "Caster level × 10 gp",
    },
    {
      name: "Spell, 2nd-level",
      cost: "Caster level × 20 gp",
    },
    {
      name: "Spell, 3rd-level",
      cost: "Caster level × 30 gp",
    },
    {
      name: "Spell, 4th-level",
      cost: "Caster level × 40 gp",
    },
    {
      name: "Spell, 5th-level",
      cost: "Caster level × 50 gp",
    },
    {
      name: "Spell, 6th-level",
      cost: "Caster level × 60 gp",
    },
    {
      name: "Spell, 7th-level",
      cost: "Caster level × 70 gp",
    },
    {
      name: "Spell, 8th-level",
      cost: "Caster level × 80 gp",
    },
    {
      name: "Spell, 9th-level",
      cost: "Caster level × 90 gp",
    },
  ],
};

export const wait = (timeout) => {
  return new Promise((resolve) => setTimeout(resolve, timeout));
};

export const getSoundEffectsMode = async () => {
  try {
    const mode = await AsyncStorage.getItem("sound-effects");
    return mode;
  } catch (ex) {
    console.log(ex);
  }
};

export const simpleWeapons = {
  unarmedAttacks: [
    {
      name: "Gauntlet",
      cost: "2 gp",
      dmgS: "1d2",
      dmgM: "1d3",
      critical: "×2",
      rangeIncrement: "-",
      weight: "1 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Gauntlet",
      cost: "—",
      dmgS: "1d2",
      dmgM: "1d3",
      critical: "×2",
      rangeIncrement: "-",
      weight: "—",
      type: "Bludgeoning",
    },
  ],
  lightMeleeWeapons: [
    {
      name: "Dagger",
      cost: "2 gp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "19-20/×2",
      rangeIncrement: "10 ft.",
      weight: "1 lb.",
      type: "Piercing or slashing",
    },
    {
      name: "Dagger, punching",
      cost: "2 gp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×3",
      rangeIncrement: "-",
      weight: "1 lb.",
      type: "Piercing",
    },
    {
      name: "Gauntlet, spiked",
      cost: "5 gp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×2",
      rangeIncrement: "-",
      weight: "1 lb.",
      type: "Piercing",
    },
    {
      name: "Mace, light",
      cost: "5 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "-",
      weight: "4 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Sickle",
      cost: "6 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "-",
      weight: "2 lb.",
      type: "Slashing",
    },
  ],
  oneHandedMeleeWeapons: [
    {
      name: "Club",
      cost: "-",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "10 ft.",
      weight: "3 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Mace, heavy",
      cost: "12 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×2",
      rangeIncrement: "-",
      weight: "8 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Morningstar",
      cost: "—",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×2",
      rangeIncrement: "-",
      weight: "6 lb.",
      type: "Bludgeoning and piercing",
    },
    {
      name: "Shortspear",
      cost: "6 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "20 ft.",
      weight: "3 lb.",
      type: "Piercing",
    },
  ],
  twoHandedMeleeWeapons: [
    {
      name: "Longspear",
      cost: "6 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×3",
      rangeIncrement: "-",
      weight: "9 lb.",
      type: "Piercing",
    },
    {
      name: "Quarterstaff",
      cost: "-",
      dmgS: "1d4/1d4",
      dmgM: "1d6/1d6",
      critical: "×2",
      rangeIncrement: "-",
      weight: "4 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Spear",
      cost: "2 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×2",
      rangeIncrement: "20 ft.",
      weight: "6 lb.",
      type: "Piercing",
    },
  ],
  rangedWeapons: [
    {
      name: "Crossbow, heavy",
      cost: "50 gp",
      dmgS: "1d8",
      dmgM: "1d10",
      critical: "19-20/×2",
      rangeIncrement: "120 ft.",
      weight: "8 lb.",
      type: "Piercing",
    },
    {
      name: "Bolts, crossbow (10)",
      cost: "1 gp",
      dmgS: "-",
      dmgM: "-",
      critical: "-",
      rangeIncrement: "-",
      weight: "1 lb.",
      type: "-",
    },
    {
      name: "Crossbow, light",
      cost: "35 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "19-20/×2",
      rangeIncrement: "80 ft.",
      weight: "4 lb.",
      type: "Piercing",
    },
    {
      name: "Bolts, crossbow (10)",
      cost: "1 gp",
      dmgS: "-",
      dmgM: "-",
      critical: "-",
      rangeIncrement: "-",
      weight: "1 lb.",
      type: "-",
    },
    {
      name: "Dart",
      cost: "5 sp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×2",
      rangeIncrement: "20 ft.",
      weight: "0.5 lb.",
      type: "Piercing",
    },
    {
      name: "Javelin",
      cost: "1 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "30 ft.",
      weight: "2 lb.",
      type: "Piercing",
    },
    {
      name: "Sling",
      cost: "—",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×2",
      rangeIncrement: "50 ft.",
      weight: "0 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Bullets, sling (10)",
      cost: "1 sp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "—",
      weight: "5 lb.",
      type: "—",
    },
  ],
};

export const martialWeapons = {
  lightMeleeWeapons: [
    {
      name: "Axe, throwing",
      cost: "8 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "10 ft.",
      weight: "2 lb.",
      type: "Slashing",
    },
    {
      name: "Hammer, light",
      cost: "1 gp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×2",
      rangeIncrement: "20 ft.",
      weight: "2 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Handaxe",
      cost: "6 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×3",
      rangeIncrement: "—",
      weight: "3 lb.",
      type: "Slashing",
    },
    {
      name: "Kukri",
      cost: "8 gp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "18-20/×2",
      rangeIncrement: "—",
      weight: "2 lb.",
      type: "Slashing",
    },
    {
      name: "Pick, light",
      cost: "4 gp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×4",
      rangeIncrement: "—",
      weight: "3 lb.",
      type: "Piercing",
    },
    {
      name: "Sap",
      cost: "1 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "—",
      weight: "2 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Shield, light",
      cost: "special",
      dmgS: "1d2",
      dmgM: "1d3",
      critical: "×2",
      rangeIncrement: "—",
      weight: "special",
      type: "Bludgeoning",
    },
    {
      name: "Spiked armor",
      cost: "special",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "—",
      weight: "special",
      type: "Piercing",
    },
    {
      name: "Spiked shield, light",
      cost: "special",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×2",
      rangeIncrement: "—",
      weight: "special",
      type: "Piercing",
    },
    {
      name: "Sword, short",
      cost: "10 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "19-20/×2",
      rangeIncrement: "—",
      weight: "2 lb.",
      type: "Piercing",
    },
  ],
  oneHandedMeleeWeapons: [
    {
      name: "Battleaxe",
      cost: "10 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×3",
      rangeIncrement: "—",
      weight: "6 lb.",
      type: "Slashing",
    },
    {
      name: "Flail",
      cost: "8 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×2",
      rangeIncrement: "—",
      weight: "5 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Longsword",
      cost: "15 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "19-20/×2",
      rangeIncrement: "—",
      weight: "4 lb.",
      type: "Slashing",
    },
    {
      name: "Pick, heavy",
      cost: "8 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×4",
      rangeIncrement: "—",
      weight: "6 lb.",
      type: "Piercing",
    },
    {
      name: "Rapier",
      cost: "20 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "18-20/×2",
      rangeIncrement: "—",
      weight: "2 lb.",
      type: "Piercing",
    },
    {
      name: "Scimitar",
      cost: "15 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "18-20/×2",
      rangeIncrement: "—",
      weight: "4 lb.",
      type: "Slashing",
    },
    {
      name: "Shield, heavy",
      cost: "special",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×2",
      rangeIncrement: "—",
      weight: "special",
      type: "Bludgeoning",
    },
    {
      name: "Spiked shield, heavy",
      cost: "special",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "—",
      weight: "special",
      type: "Piercing",
    },
    {
      name: "Trident",
      cost: "15 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×2",
      rangeIncrement: "10 ft.",
      weight: "4 lb.",
      type: "Piercing",
    },
    {
      name: "Warhammer",
      cost: "12 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×3",
      rangeIncrement: "—",
      weight: "5 lb.",
      type: "Bludgeoning",
    },
  ],
  twoHandedMeleeWeapons: [
    {
      name: "Falchion",
      cost: "75 gp",
      dmgS: "1d6",
      dmgM: "2d4",
      critical: "18-20/×2",
      rangeIncrement: "—",
      weight: "8 lb.",
      type: "Slashing",
    },
    {
      name: "Glaive",
      cost: "8 gp",
      dmgS: "1d8",
      dmgM: "1d10",
      critical: "×3",
      rangeIncrement: "—",
      weight: "10 lb.",
      type: "Slashing",
    },
    {
      name: "Greataxe",
      cost: "20 gp",
      dmgS: "1d10",
      dmgM: "1d12",
      critical: "×3",
      rangeIncrement: "—",
      weight: "12 lb.",
      type: "Slashing",
    },
    {
      name: "Greatclub",
      cost: "5 gp",
      dmgS: "1d8",
      dmgM: "1d10",
      critical: "×2",
      rangeIncrement: "—",
      weight: "8 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Flail, heavy",
      cost: "15 gp",
      dmgS: "1d8",
      dmgM: "1d10",
      critical: "19-20/×2",
      rangeIncrement: "—",
      weight: "10 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Greatsword",
      cost: "50 gp",
      dmgS: "1d10",
      dmgM: "2d6",
      critical: "19-20/×2",
      rangeIncrement: "—",
      weight: "8 lb.",
      type: "Slashing",
    },
    {
      name: "Guisarme",
      cost: "9 gp",
      dmgS: "1d6",
      dmgM: "2d4",
      critical: "×3",
      rangeIncrement: "—",
      weight: "12 lb.",
      type: "Slashing",
    },
    {
      name: "Halberd",
      cost: "10 gp",
      dmgS: "1d8",
      dmgM: "1d10",
      critical: "×3",
      rangeIncrement: "—",
      weight: "12 lb.",
      type: "Piercing or slashing",
    },
    {
      name: "Lance",
      cost: "10 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×3",
      rangeIncrement: "—",
      weight: "10 lb.",
      type: "Piercing",
    },
    {
      name: "Ranseur",
      cost: "10 gp",
      dmgS: "1d6",
      dmgM: "2d4",
      critical: "×3",
      rangeIncrement: "—",
      weight: "12 lb.",
      type: "Piercing",
    },
    {
      name: "Scythe",
      cost: "18 gp",
      dmgS: "1d6",
      dmgM: "2d4",
      critical: "×4",
      rangeIncrement: "—",
      weight: "10 lb.",
      type: "Piercing or slashing",
    },
  ],
  rangedWeapons: [
    {
      name: "Longbow",
      cost: "75 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×3",
      rangeIncrement: "100 ft.",
      weight: "3 lb.",
      type: "Piercing",
    },
    {
      name: "Arrows (20)",
      cost: "1 gp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "—",
      weight: "3 lb.",
      type: "—",
    },
    {
      name: "Longbow, composite",
      cost: "100 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "×3",
      rangeIncrement: "110 ft.",
      weight: "3 lb.",
      type: "Piercing",
    },
    {
      name: "Arrows (20)",
      cost: "1 gp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "—",
      weight: "3 lb.",
      type: "—",
    },
    {
      name: "Shortbow",
      cost: "30 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×3",
      rangeIncrement: "60 ft.",
      weight: "2 lb.",
      type: "Piercing",
    },
    {
      name: "Arrows (20)",
      cost: "1 gp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "—",
      weight: "3 lb.",
      type: "—",
    },
    {
      name: "Shortbow, composite",
      cost: "75 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×3",
      rangeIncrement: "70 ft.",
      weight: "2 lb.",
      type: "Piercing",
    },
    {
      name: "Arrows (20)",
      cost: "1 gp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "—",
      weight: "3 lb.",
      type: "—",
    },
  ],
};

export const exoticWeapons = {
  lightMeleeWeapons: [
    {
      name: "Kama",
      cost: "2 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "—",
      weight: "2 lb.",
      type: "Slashing",
    },
    {
      name: "Nunchaku",
      cost: "2 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "—",
      weight: "2 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Sai",
      cost: "1 gp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "×2",
      rangeIncrement: "10 ft.",
      weight: "1 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Siangham",
      cost: "3 gp",
      dmgS: "1d4",
      dmgM: "1d6",
      critical: "×2",
      rangeIncrement: "—",
      weight: "1 lb.",
      type: "Piercing",
    },
  ],
  oneHandedMeleeWeapons: [
    {
      name: "Sword, bastard",
      cost: "35 gp",
      dmgS: "1d8",
      dmgM: "1d10",
      critical: "19-20/×2",
      rangeIncrement: "—",
      weight: "6 lb.",
      type: "Slashing",
    },
    {
      name: "Waraxe, dwarven",
      cost: "30 gp",
      dmgS: "1d8",
      dmgM: "1d10",
      critical: "×3",
      rangeIncrement: "—",
      weight: "8 lb.",
      type: "Slashing",
    },
    {
      name: "Whip",
      cost: "1 gp",
      dmgS: "1d2",
      dmgM: "1d3",
      critical: "×2",
      rangeIncrement: "—",
      weight: "2 lb.",
      type: "Slashing",
    },
  ],
  twoHandedMeleeWeapons: [
    {
      name: "Axe, orc double</a><sup>5",
      cost: "60 gp",
      dmgS: "1d6/1d6",
      dmgM: "1d8/1d8",
      critical: "×3",
      rangeIncrement: "—",
      weight: "15 lb.",
      type: "Slashing",
    },
    {
      name: "Chain, spiked",
      cost: "25 gp",
      dmgS: "1d6",
      dmgM: "2d4",
      critical: "×2",
      rangeIncrement: "—",
      weight: "10 lb.",
      type: "Piercing",
    },
    {
      name: "Flail, dire",
      cost: "90 gp",
      dmgS: "1d6/1d6",
      dmgM: "1d8/1d8",
      critical: "×2",
      rangeIncrement: "—",
      weight: "10 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Hammer, gnome hooked",
      cost: "20 gp",
      dmgS: "1d6/1d4",
      dmgM: "1d8/1d6",
      critical: "×3/×4",
      rangeIncrement: "—",
      weight: "6 lb.",
      type: "Bludgeoning/Piercing",
    },
    {
      name: "Sword, two-bladed",
      cost: "100 gp",
      dmgS: "1d6/1d6",
      dmgM: "1d8/1d8",
      critical: "19-20/×2",
      rangeIncrement: "—",
      weight: "10 lb.",
      type: "Slashing",
    },
    {
      name: "Urgrosh, dwarven",
      cost: "50 gp",
      dmgS: "1d6/1d4",
      dmgM: "1d8/1d6",
      critical: "×3",
      rangeIncrement: "—",
      weight: "12 lb.",
      type: "Slashing or piercing",
    },
  ],
  rangedWeapons: [
    {
      name: "Bolas",
      cost: "5 gp",
      dmgS: "1d3<sup>3</sup>",
      dmgM: "1d4<sup>3</sup>",
      critical: "×2",
      rangeIncrement: "10 ft.",
      weight: "2 lb.",
      type: "Bludgeoning",
    },
    {
      name: "Crossbow, hand",
      cost: "100 gp",
      dmgS: "1d3",
      dmgM: "1d4",
      critical: "19-20/×2",
      rangeIncrement: "30 ft.",
      weight: "2 lb.",
      type: "Piercing",
    },
    {
      name: "Bolts (10)",
      cost: "1 gp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "—",
      weight: "1 lb.",
      type: "—",
    },
    {
      name: "Crossbow, repeating heavy",
      cost: "400 gp",
      dmgS: "1d8",
      dmgM: "1d10",
      critical: "19-20/×2",
      rangeIncrement: "120 ft.",
      weight: "12 lb.",
      type: "Piercing",
    },
    {
      name: "Bolts (5)",
      cost: "1 gp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "—",
      weight: "1 lb.",
      type: "—",
    },
    {
      name: "Crossbow, repeating light",
      cost: "250 gp",
      dmgS: "1d6",
      dmgM: "1d8",
      critical: "19-20/×2",
      rangeIncrement: "80 ft.",
      weight: "6 lb.",
      type: "Piercing",
    },
    {
      name: "Bolts (5)",
      cost: "1 gp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "—",
      weight: "1 lb.",
      type: "—",
    },
    {
      name: 'Net',
      cost: "20 gp",
      dmgS: "—",
      dmgM: "—",
      critical: "—",
      rangeIncrement: "10 ft.",
      weight: "6 lb.",
      type: "—",
    },
    {
      name: 'Shuriken (5)',
      cost: "1 gp",
      dmgS: "1",
      dmgM: "1d2",
      critical: "×2",
      rangeIncrement: "10 ft.",
      weight: "0.5 lb.",
      type: "Piercing",
    },
  ],
};



export const ip = 'https://9aa4-2a02-214a-8329-3700-5c54-aa6d-177a-15c6.eu.ngrok.io/gateway'